name: CI (Python Multi-OS/Version)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[dev] || true
          pip install flake8 pylint pytest

      - name: Convert CRLF to LF
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix
          find . -type f -name "*.py" -exec dos2unix {} \;

      - name: Run flake8
        run: flake8 tkface tests

      - name: Run pylint
        run: pylint tkface tests

      - name: Run pytest
        run: pytest -q --maxfail=1 --disable-warnings -v
